server:
  port: 8081

spring:
  mongodb:
    host: localhost
    port: 27017
    database: craftstudio-mes
    username: craftstudio-mes-admin
    password: "craftstudiomes13579"
    authentication-database: admin
  data:
    redis:
      host: 47.97.82.26
      port: 8012
      database: 0
      password: Ysd@950421      ## Redis服务器连接密码
      timeout: 3000
      pool:
        max-idle: 8               ## 连接池中的最大空闲连接
        min-idle: 1               ## 连接池中的最小空闲连接
        max-active: 8             ## 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1              ## 连接池最大阻塞等待时间（使用负值表示没有限制）

#logging:
#  level:
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
#    org.mongodb.driver: DEBUG