server:
  port: 8081

spring:
  #多环境配置
  profiles:
    active: test
  mongodb:
    host: localhost
    port: 27017
    database: craftstudio-mes
    username: craftstudio-mes-admin
    password: "craftstudiomes13579"
    authentication-database: admin

# 外部系统 API 配置
external:
  api:
    baseUrl: http://external-system.com/api/v1

#logging:
#  level:
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
#    org.mongodb.driver: DEBUG