server:
  port: 80

spring:
  mongodb:
    host: localhost
    port: 27017
    database: craftstudio-mes
    username: craftstudio-mes-admin
    password: "7I02^x33hB9.*]ex0"
    authentication-database: admin
