server:
  port: 8081

spring:
  #多环境配置
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  mongodb:
    host: localhost
    port: 27017
    database: craftstudio-mes
    username: craftstudio-mes-admin
    password: "craftstudiomes13579"
    authentication-database: admin

# 外部系统 API 配置
external:
  api:
    productCoreUrl: http://8.136.34.126:80
    algorithmUrl: http://craftstg-masker-qvsnfcgkck.cn-hangzhou.fcapp.run
  callbackApi:
    generate_mask_files: http://121.40.134.45:8081/api/manufacturerSide/order/callback/generate_mask_files
    
oss:
  endpoint: https://oss-cn-hangzhou.aliyuncs.com
  bucket-name: craftstudio-mes-test
  save-path: test



#logging:
#  level:
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
#    org.mongodb.driver: DEBUG